'use client'

import { useEffect, useState } from 'react'
import { ArrowDown, ArrowUpRight, ChevronRight, CircleHelp, Clock3, Menu, X } from 'lucide-react'
import { site } from '@/config/site'

function SceneBackground({ src, tone = 'hero' }: { src: string; tone?: string }) {
  return <div className={`scene scene-${tone}`} aria-hidden="true" style={{ '--scene-image': `url(${src})` } as React.CSSProperties}><svg className="scene-fallback" viewBox="0 0 1200 700" preserveAspectRatio="xMidYMid slice"><defs><radialGradient id={`glow-${tone}`}><stop stopColor="#ffd58a" stopOpacity=".9" /><stop offset="1" stopColor="#ff7aa2" stopOpacity="0" /></radialGradient></defs><circle cx="600" cy="180" r="260" fill={`url(#glow-${tone})`} /><path d="M0 470 220 300 430 470 700 250 940 470 1200 320V700H0Z" fill="#17244d" /><path d="M0 540 250 390 510 540 800 350 1200 520V700H0Z" fill="#0c1635" /><path d="M0 620 300 470 610 590 900 430 1200 560V700H0Z" fill="#070b21" /></svg><div className="scene-image" /><div className="sun" /><div className="cloud cloud-a" /><div className="cloud cloud-b" /><div className="island island-a"><i /><i /><i /></div><div className="island island-b"><i /><i /></div><div className="ridge" /><div className="cliff" /><div className="mist mist-a" /><div className="mist mist-b" /><div className="scene-stars" /><div className="scene-motes" /></div>
}

function Frame({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <div className={`hud-frame ${className}`}>{children}</div> }

function Countdown() {
  const [left, setLeft] = useState({ d: '072', h: '18', m: '42', s: '09' })
  useEffect(() => { const tick = () => { const diff = Math.max(0, new Date(site.eventDate).getTime() - Date.now()); const d = Math.floor(diff / 86400000); const h = Math.floor(diff / 3600000) % 24; const m = Math.floor(diff / 60000) % 60; const s = Math.floor(diff / 1000) % 60; setLeft({ d: String(d).padStart(3, '0'), h: String(h).padStart(2, '0'), m: String(m).padStart(2, '0'), s: String(s).padStart(2, '0') }) }; tick(); const id = setInterval(tick, 1000); return () => clearInterval(id) }, [])
  return <div className="countdown" aria-label="Countdown to Techfest"><Clock3 size={15} /><div><strong>{left.d}</strong><small>DAYS</small></div><b>:</b><div><strong>{left.h}</strong><small>HRS</small></div><b>:</b><div><strong>{left.m}</strong><small>MIN</small></div><b>:</b><div><strong>{left.s}</strong><small>SEC</small></div></div>
}

export default function Page() {
  const [menu, setMenu] = useState(false)
  const [realm, setRealm] = useState(0)
  const [email, setEmail] = useState('')
  const [sent, setSent] = useState(false)
  return <main className="techfest-site">
    <a className="skip-link" href="#content">Skip to content</a>
    <header className="topbar"><a className="monogram" href="#top">TF<span>30</span></a><nav>{site.nav.map((item, i) => <a key={item} href={i === 1 ? '#realms' : '#footer'}>{item}{item === 'Workshops' && <em>EARLY BIRD</em>}</a>)}</nav><a className="signin" href="#footer">Sign In <ArrowUpRight size={15} /></a><button className="menu-btn" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? <X /> : <Menu />}</button></header>
    {menu && <div className="mobile-menu"><p>Navigate the realms</p>{site.nav.map(x => <a key={x} href="#realms" onClick={() => setMenu(false)}>{x}<ChevronRight /></a>)}</div>}
    <aside className="dock"><a className="active" href="#top">01<span>Home</span></a><a href="#realms">02<span>Events</span></a><a href="#about">03<span>About</span></a><a href="#footer">04<span>Contact</span></a></aside>
    <section className="hero" id="top"><SceneBackground src="/scenes/hero.webp" /><div className="hero-content"><p className="eyebrow">{site.hero.eyebrow} <span>// 30 YEARS OF TOMORROW</span></p><div className="hero-title-wrap"><h1 data-title={site.hero.title}>{site.hero.title.split('').map((c, i) => <span key={i} style={{ animationDelay: `${i * 60}ms` }}>{c}</span>)}</h1></div><p className="hero-date">{site.hero.date}</p><p className="hero-subtitle">{site.hero.subtitle}</p><p className="theme">{site.hero.theme}</p><Countdown /><div className="hero-actions"><a className="gold-btn" href="#realms">Register now <ArrowUpRight size={16} /></a><a className="text-btn" href="#realms">Explore realms <ArrowDown size={16} /></a></div></div><div className="hero-side">AETHER<br /><b>01</b><span>scroll to descend</span></div><div className="scroll-cue"><span /> SCROLL TO DESCEND</div></section>
    <div id="content" className="portal-wrap">{site.portals.map((p, i) => <Frame key={p.label} className={i === 1 ? 'portal-main' : ''}><p className="card-label">{p.label}</p><h2>{p.title}</h2><p>{p.body}</p><a href="#realms">{p.action} <ArrowUpRight size={14} /></a></Frame>)}</div>
    <section className="stats scene-section"><SceneBackground src="/scenes/workshops.webp" tone="workshops" /><div className="section-kicker">THE SIGNAL / 30.00</div>{site.stats.map(s => <div key={s.label}><strong>{s.value}</strong><span>{s.label}</span></div>)}</section>
    <section className="about section-pad scene-section" id="about"><SceneBackground src="/scenes/lectures.webp" tone="lectures" /><div className="section-copy"><p className="section-kicker">THE ORIGIN STORY / 1998—2026</p><h2>Built by students.<br /><i>Powered by wonder.</i></h2><p>For three decades, Techfest has been a meeting point for restless minds. A student-organised constellation from IIT Bombay, now orbiting ideas across the world.</p><div className="badge-row"><span>UNESCO<br /><small>PATRONAGE</small></span><span>UNICEF<br /><small>PATRONAGE</small></span><span>GUINNESS<br /><small>WORLD RECORD</small></span></div></div><div className="core-orbit"><div className="core">TF</div><div className="orbit orbit-1" /><div className="orbit orbit-2" /><span className="orbit-label">AETHER CORE<br /><b>ACTIVE</b></span></div></section>
    <section className="realms scene-section" id="realms"><SceneBackground src="/scenes/competitions.webp" tone="competitions" /><div className="realm-intro section-pad"><p className="section-kicker">THE GATES / SELECT A REALM</p><h2>Where ideas<br /><i>become worlds.</i></h2></div><div className="realm-stage"><SceneBackground src={`/scenes/${site.realms[realm].name.toLowerCase()}.webp`} tone={`realm-${realm}`} /><div className="realm-list">{site.realms.map((r, i) => <button key={r.name} className={realm === i ? 'selected' : ''} onClick={() => setRealm(i)}><span>0{i + 1}</span>{r.name}<ChevronRight /></button>)}</div><Frame className="realm-card"><p className="card-label" style={{ color: site.realms[realm].color }}>{site.realms[realm].kicker}</p><h3>{site.realms[realm].name}</h3><p>{site.realms[realm].body}</p><a className="gold-btn" href="#footer">{site.realms[realm].action} <ArrowUpRight size={15} /></a></Frame></div><div className="explore section-pad"><p className="section-kicker">MORE TO EXPLORE</p><div className="explore-grid">{site.explore.map((x, i) => <a href="#footer" key={x} className={`explore-tile tile-${i}`}><span>0{i + 1}</span><h3>{x}</h3><ArrowUpRight /></a>)}</div></div></section>
    <section className="technoholix scene-section"><SceneBackground src="/scenes/exhibitions.webp" tone="exhibitions" /><div className="neon-lines" /><p className="section-kicker">A NIGHT OF ELECTRIC POSSIBILITY</p><h2>TECHNO<span>HOLIX</span></h2><p>Lights down. Frequencies up. The future is loud.</p><div className="equalizer">{Array.from({ length: 18 }).map((_, i) => <i key={i} style={{ animationDelay: `${i * 80}ms` }} />)}</div></section>
    <section className="timeline section-pad scene-section"><SceneBackground src="/scenes/ignite.webp" tone="ignite" /><p className="section-kicker">THE ARCHIVE / A LIVING LEGACY</p><h2>Thirty years<br /><i>in orbit.</i></h2><div className="timeline-track">{site.milestones.map(([year, text]) => <div key={year}><strong>{year}</strong><span>{text}</span></div>)}</div></section>
    <section className="final-cta section-pad scene-section"><SceneBackground src="/scenes/hero.webp" tone="cta" /><p className="section-kicker">THE NEXT CHAPTER</p><h2>Be part of<br /><i>the future.</i></h2>{sent ? <div className="success">Signal received. Watch your inbox.</div> : <form onSubmit={e => { e.preventDefault(); if (email.includes('@')) setSent(true) }}><input required type="email" placeholder="your@email.com" value={email} onChange={e => setEmail(e.target.value)} aria-label="Email address" /><button className="gold-btn">Transmit <ArrowUpRight size={15} /></button></form>}<div className="footer-note">Updates from the aether · no noise</div></section>
    <footer id="footer"><div><a className="monogram" href="#top">TF<span>30</span></a><p>Indian Institute of Technology Bombay<br />Powai, Mumbai</p></div><div><p className="section-kicker">FOLLOW THE SIGNAL</p><div className="socials">{site.footer.map(x => <a href="#footer" key={x} aria-label={x}>{x[0]}</a>)}</div></div><p className="copyright">© 2026 Techfest, IIT Bombay<br />All systems nominal.</p></footer><button className="drone" aria-label="Ask Techfest"><CircleHelp /></button>
  </main>
}
